title: "Coastal & Ocean Science Lab Team"
description: "@ The University of Queensland"
theme: jekyll-theme-minimal
markdown: kramdown
sass:
  style: compressed

stylesheets:
  - "/assets/css/style.css"
